Add support for AllowsAirRoutes building flag
LoneGazebo/Community-Patch-DLL pull request #10683
Opened 2024-02-25 13:04 UTC by KungCheops

City connection is blocked if the city is blockaded by water and land.

2024-02-25 15:20 UTC, LessRekkless approved these changes

2024-02-25 16:48 UTC, LessRekkless requested changes
Actually, we [will] need an update the to City Connections entries in the Civilopedia [when airport gains AllowsAirRoutes]:
TXT_KEY_GOLD_TRADE_ROUTES_HEADING3_BODY
TXT_KEY_WORKERS_TRADEROUTES_HEADING3_BODY
TXT_KEY_HAPPINESS_CAUSESUNHAPPINESS_HEADING2_BODY

2024-02-25 16:52 UTC, LessRekkless approved these changes
Nevermind.  This is a problem for when a building actually gains AllowsAirRoutes.

2024-02-26 00:54 UTC, azum4roll commented on CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp
> +			iLocalBonus -= 50;
Surely this should be a positive instead if the city isn't connected, and 0 if it is?

2024-02-26 11:34 UTC, KungCheops commented on CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp
> +			iLocalBonus -= 50;
I copied this from the lighthouse logic. I agree that it's quite strange.

2024-02-26 11:35 UTC, KungCheops commented on CvGameCoreDLL_Expansion2/CvBuildingProductionAI.cpp
> +			iLocalBonus -= 50;
But I didn't want building AI logic to be in the scope of this change so I just made a primitive version for now.

2024-03-19 01:31 UTC, merged