'Bonus vs. Armored Units (50)' instead of 'Anti-Tank Rounds'
LoneGazebo/Community-Patch-DLL pull request #8677
Opened 2022-02-21 14:11 UTC by nobubblegums

'TXT_KEY_PROMOTION_ANTI_TANK_HELP' doesn't exist in the database, so the title Anti-Tank Rounds wasn't really descriptive. I tried inserting the help key, but couldn't do it for some reason, so I just changed the title to a format used by many promotions. I don't think this needs a help text anyway. Stackedpromotions also prevent duplicate texts from being shown in the unitpanel when title = help, so it doesn't look bad either.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/8675

2022-02-21 19:41 UTC, LessRekkless requested changes
instead of making this change, instead replace lines 244-246
```
UPDATE Language_en_US
	SET Text = '+50% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].'
	WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK_HELP';
```
with
```
INSERT INTO Language_en_US (Tag, Text)
VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '+50% [ICON_STRENGTH] Combat Strength VS [COLOR_POSITIVE_TEXT]Armored Units[ENDCOLOR].')
```

2022-02-22 09:59 UTC, nobubblegums commented
Yeah I tried that first, for some reason couldn't get that working. It seems simple enough and I can't figure out what's going wrong, maybe something's off with my local files, so I kinda gave up. Could you do it, I can close this PR in that case

2022-02-22 18:15 UTC, LessRekkless commented
The entry in PromotionChanges.xml wasn't pointing to the help text (that didn't exist).  See #8680.

2022-02-22 19:46 UTC, nobubblegums commented
Nice, closing this now

2022-02-22 19:46 UTC, closed without merging